
package br.com.bradseg.bucb.crivoauto.service.response;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.bradseg.bucb.crivoauto.delegate.CrivoServiceDelegate;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CrivoService", targetNamespace = "http://service.crivoauto.bucb.bradseg.com.br/", wsdlLocation = "http://wsphttp.dsv.bradseg.com.br/BUCB-CrivoAuto/services/CrivoService/wsdl/CrivoService.wsdl")
public class CrivoService
    extends Service
{

    private final static URL CRIVOSERVICE_WSDL_LOCATION;
    private final static WebServiceException CRIVOSERVICE_EXCEPTION;
    private final static QName CRIVOSERVICE_QNAME = new QName("http://service.crivoauto.bucb.bradseg.com.br/", "CrivoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://wsphttp.dsv.bradseg.com.br/BUCB-CrivoAuto/services/CrivoService/wsdl/CrivoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CRIVOSERVICE_WSDL_LOCATION = url;
        CRIVOSERVICE_EXCEPTION = e;
    }

    public CrivoService() {
        super(__getWsdlLocation(), CRIVOSERVICE_QNAME);
    }

    public CrivoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CRIVOSERVICE_QNAME, features);
    }

    public CrivoService(URL wsdlLocation) {
        super(wsdlLocation, CRIVOSERVICE_QNAME);
    }

    public CrivoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CRIVOSERVICE_QNAME, features);
    }

    public CrivoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrivoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CrivoServiceDelegate
     */
    @WebEndpoint(name = "CrivoServicePort")
    public CrivoServiceDelegate getCrivoServicePort() {
        return super.getPort(new QName("http://service.crivoauto.bucb.bradseg.com.br/", "CrivoServicePort"), CrivoServiceDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrivoServiceDelegate
     */
    @WebEndpoint(name = "CrivoServicePort")
    public CrivoServiceDelegate getCrivoServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.crivoauto.bucb.bradseg.com.br/", "CrivoServicePort"), CrivoServiceDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CRIVOSERVICE_EXCEPTION!= null) {
            throw CRIVOSERVICE_EXCEPTION;
        }
        return CRIVOSERVICE_WSDL_LOCATION;
    }

}
