

package br.com.bradseg.bucb.crivoauto.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BUCBCrivoException", targetNamespace = "http://service.crivoauto.bucb.bradseg.com.br/")
public class BUCBCrivoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BUCBCrivoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BUCBCrivoException_Exception(String message, BUCBCrivoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BUCBCrivoException_Exception(String message, BUCBCrivoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.com.bradseg.bucb.crivoauto.service.BUCBCrivoException
     */
    public BUCBCrivoException getFaultInfo() {
        return faultInfo;
    }

}
