
package br.com.bradseg.bucb.crivoauto.delegate;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import br.com.bradseg.bucb.crivoauto.exception.BUCBCrivoException_Exception;
import br.com.bradseg.bucb.crivoauto.po.ConsultaCrivoPO;
import br.com.bradseg.bucb.crivoauto.po.ExecutaOperacaoCrivoPO;
import br.com.bradseg.bucb.crivoauto.util.ObjectFactory;
import br.com.bradseg.bucb.crivoauto.vo.ParametroSaidaVO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CrivoServiceDelegate", targetNamespace = "http://service.crivoauto.bucb.bradseg.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CrivoServiceDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<br.com.bradseg.bucb.crivoauto.service.ParametroSaidaVO>
     * @throws BUCBCrivoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "executaOperacaoAuto", targetNamespace = "http://service.crivoauto.bucb.bradseg.com.br/", className = "br.com.bradseg.bucb.crivoauto.service.ExecutaOperacaoAuto")
    @ResponseWrapper(localName = "executaOperacaoAutoResponse", targetNamespace = "http://service.crivoauto.bucb.bradseg.com.br/", className = "br.com.bradseg.bucb.crivoauto.service.ExecutaOperacaoAutoResponse")
    public List<ParametroSaidaVO> executaOperacaoAuto(
        @WebParam(name = "arg0", targetNamespace = "")
        ExecutaOperacaoCrivoPO arg0)
        throws BUCBCrivoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws BUCBCrivoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "executaOperacaoObjAnaliseAuto", targetNamespace = "http://service.crivoauto.bucb.bradseg.com.br/", className = "br.com.bradseg.bucb.crivoauto.service.ExecutaOperacaoObjAnaliseAuto")
    @ResponseWrapper(localName = "executaOperacaoObjAnaliseAutoResponse", targetNamespace = "http://service.crivoauto.bucb.bradseg.com.br/", className = "br.com.bradseg.bucb.crivoauto.service.ExecutaOperacaoObjAnaliseAutoResponse")
    public List<String> executaOperacaoObjAnaliseAuto(
        @WebParam(name = "arg0", targetNamespace = "")
        ExecutaOperacaoCrivoPO arg0)
        throws BUCBCrivoException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<br.com.bradseg.bucb.crivoauto.service.ParametroSaidaVO>
     * @throws BUCBCrivoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaCrivoAuto", targetNamespace = "http://service.crivoauto.bucb.bradseg.com.br/", className = "br.com.bradseg.bucb.crivoauto.service.ConsultaCrivoAuto")
    @ResponseWrapper(localName = "consultaCrivoAutoResponse", targetNamespace = "http://service.crivoauto.bucb.bradseg.com.br/", className = "br.com.bradseg.bucb.crivoauto.service.ConsultaCrivoAutoResponse")
    public List<ParametroSaidaVO> consultaCrivoAuto(
        @WebParam(name = "arg0", targetNamespace = "")
        ConsultaCrivoPO arg0)
        throws BUCBCrivoException_Exception
    ;

}
